In [20]:
import pandas as pd

df1=pd.read_csv('planId_1565082058_data.csv',index_col=False)
df2=pd.read_csv('planId_1565082062_data.csv',index_col=False)

In [21]:
df2.groupby(['loanStatusText']).sum()

,Unnamed: 0,loanId,intRate,remainingPaymentsCount,subTypeText,holdingAmount,loanTotalTerms,loanPaidTerms,appAmount,todayData
loanStatusText,,,,,,,,,,
坏账,6151,171394552,3.6733,735,0.0,7702.69,933,198,2565271.67,False
宽限期中,260,6313282,0.1013,23,0.0,300.26,36,13,149280.40,False
本期偿清,10534,298780221,4.9736,899,0.0,13227.97,1510,611,6878115.73,False
逾期,1932,57062738,0.4527,15,0.0,891.64,37,22,1275869.40,False

In [11]:
df2.sum()

Unnamed: 0                                                            34453
loanId                                                           1558028431
loanStatus                CURRENTCURRENTDEFAULTEDDELINQUENTCURRENTDEFAUL...
loanStatusText            本期偿清本期偿清坏账逾期本期偿清坏账本期偿清逾期本期偿清本期偿清本期偿清坏账坏账本期偿清本期...
intRate                                                             33.1667
loanClass                 A1A1A3B4C5D4C3B4B1A3B1A3C5C3A3C3D4E3B4A2B4B4B4...
remainingPaymentsCount                                                 4967
subType                   ULOANSPEED_LOANOUTSTANDINGMCA_GREENLANE_OFFLIN...
subTypeText                                                               0
holdingAmount                                                       49609.8
loanTotalTerms                                                         8404
loanPaidTerms                                                          3437
appAmount                                                        3.3368e+07
classification            PERSONALPERSONALPERSONALPERSONALPERSONALPERSON...
todayData                                                             False
dtype: object

In [22]:
df1.groupby(['loanStatusText']).sum()

,Unnamed: 0,loanId,intRate,remainingPaymentsCount,subTypeText,holdingAmount,loanTotalTerms,loanPaidTerms,appAmount,todayData
loanStatusText,,,,,,,,,,
坏账,6500,395237175,10.4221,1745,0.0,13692.11,2424,679,7936776.74,False
本期偿清,7590,499127900,11.0815,1289,0.0,10963.21,2935,1646,11272798.93,False
还款中,541,35726774,0.8395,86,0.0,915.57,181,95,783290.57,False
逾期,945,94385789,1.6227,175,0.0,1916.39,348,173,2506607.87,False

In [8]:
df.sum()

Unnamed: 0                                                            15576
loanId                                                           1024477638
loanStatus                CURRENTCURRENTDEFAULTEDDELINQUENTCURRENTDEFAUL...
loanStatusText            本期偿清本期偿清坏账逾期本期偿清坏账本期偿清逾期本期偿清本期偿清本期偿清坏账坏账本期偿清本期...
intRate                                                             23.9658
loanClass                 A1A1A3B4C5D4C3B4B1A3B1A3C5C3A3C3D4E3B4A2B4B4B4...
remainingPaymentsCount                                                 3295
subType                   ULOANSPEED_LOANOUTSTANDINGMCA_GREENLANE_OFFLIN...
subTypeText                                                               0
holdingAmount                                                       27487.3
loanTotalTerms                                                         5888
loanPaidTerms                                                          2593
appAmount                                                       2.24995e+07
classification            PERSONALPERSONALPERSONALPERSONALPERSONALPERSON...
todayData                                                             False
dtype: object